version: '3.7'

services:
  notification_service:
    image: notification-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db1:3306/notifications?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: cefalo
      SPRING_DATASOURCE_PASSWORD: cefalo_notifications
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SMSINTEGRATIONMESSAGE: smsintegrationmessage
      EMAILINTEGRATIONMESSAGE: emailintegrationmessage
    networks:
      - notification_service
      - service-rabbitmq

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: notifications
      MYSQL_USER: cefalo
      MYSQL_PASSWORD: cefalo_notifications
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - db-data:/var/lib/mysql
    networks:
      - notification_service

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - service-rabbitmq
volumes:
  db-data:
networks:
  notification_service:
  service-rabbitmq:



